import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "./layout.module.css"
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <header className={styles.header}>
          <nav>
            <Link href="/">Strona główna</Link> 
            <Link href="/about">O mnie</Link> 
            <Link href="/contact">Kontakt</Link>
          </nav>
        </header>

        <main className="styles.main">{children}</main>
        <footer className={styles.footer}>Mój stopka © 2025</footer>
        </body>
    </html>
  );
}
