import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
 
      <body className={`${geistSans.variable} ${geistMono.variable} ${styles.body}`}>
       <header className={styles.headerWrapper}>
  <h1 className={styles.header}>Witaj</h1>
  <nav className={styles.navbar}>
    <ul>
      <li><a href="/">Strona główna</a></li>
      <li><a href="/o-mnie">O mnie</a></li>
      <li><a href="/kontakt">Kontakt</a></li>
    </ul>
  </nav>
</header>
    <main>
      {children}
    </main>
     <footer className={styles.footer}>
      <p>kontakt: mail@op.pl</p>
    </footer>
      </body>
    </html>
  );
}