import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Link from "next/link";
import Menu from "./components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems = [
  {
    text: "strona główna",
    url: "/",
    children: [
      {
        text: "o mnie",
        url: "/about-me",
      },
    ],
  },
  {
    text: "kontakt",
    url: "/contact",
  },
];



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
 
      <body className={`${geistSans.variable} ${geistMono.variable} ${styles.body}`}>
       <header className={styles.headerWrapper}>
  <h1 className={styles.header}>Witaj</h1>
  <nav className={styles.navbar}>
  <Menu items={menuItems} />
  </nav>
</header>
    <main>
      {children}
    </main>
     <footer className={styles.footer}>
      <p>kontakt: mail@op.pl</p>
    </footer>
      </body>
    </html>
  );
}